### ISSUE TITLE
cacher removed from cran

### ISSUE THREAD

**Issue by bosr** [rdpeng/cacher#1]
Hi Roger,

First of all, thank you for your Coursera Data Science Specialisation, and especially your work around reproducible research. I admire the kind of patience and determination it takes to make these ideas grow. 

`cacher` was a good idea: I could not find a reason why it was removed from CRAN, would you please explain? 

Furthermore, it still works well: installing the package with `devtools::install_github` gave me a perfectly working package on OSX 10.11 with R 3.2.2. I could follow the 2007 tutorial you made.

I hope `cacher` has been superseded, or can be rehabilitated.

Best regards

**Comment by friendimaginary** [comment]
According to CRAN, "Package ‘cacher’ was removed from the CRAN repository ... on 2014-09-19 as vignette locations were never updated for R 3.1.0."

I guess that means that while it didn't necessarily become incompatible, it wasn't updated to ensure compatibility.
